name: Test Workflow

on: [push, workflow_dispatch]

jobs:
  Job1:
    name: My Job1
    runs-on: windows-latest
    
    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in GitHub"
      - run: echo "The code is being trigger by ${{ github.repository_owner }}"
      - name: Check out source code
        uses: actions/checkout@v2.4.0
      - run: echo "This repo is ${{ github.repository }} .."
#      - name: Find top 20 largest folders
#        run: |
#          #gci "C:\" -r -Exclude "*Windows Defender*" | sort-object Length -Descending | Select Length,fullname -f 20
#        shell: pwsh      
#      - name: Clean up docker cache on windows
#        run: |
#         docker system prune -af      
#        shell: bash
      - name: Run a inline script
        run: |
          mkdir newfolder
          ls -l
        shell: bash
      - name: Run a script file from repo
        if: ${{ always() }}
        run: sh ./.github/workflows/run.sh
        shell: pwsh
      - name: Execute during failure
        if: ${{ failure() }}
        run: echo "One of the step seems failed"
      - name: Run Selenium Test
        if: ${{ env.SELENIUM_DRIVER == 'RemoteWebDriver' }}
        run: echo "Running test in Selenium grid setup"
        
        
  Job2:
    name:  Test Job 2
    runs-on: ubuntu-latest
    needs: Job1
    if: ${{ always() }}
    
    steps:
      - run: echo "This is from second job"
    
         
      
